### PR TITLE
gen: prevent generated tests from calling t.Logf with struct as argument, fixing go vet copylocks error when struct has sync.Mutex field - #255

### PR DESCRIPTION
**Pull request by shawnps-sigsci**
https://github.com/tinylib/msgp/issues/255

### CODE REVIEW

**Comment by philhofer** [comment]
Code change itself LGTM. Would love to have a test case as well (there are other script-driven test cases in the _generated directory you can take a peek at; I think you can just add the repro type definition and then stick `//go:generate go vet` in the file after the `//go:generate msgp` line).

**Comment by shawnps-sigsci** [comment]
@philhofer unfortunately that surfaced some `go vet` errors in the actual generated code as well:

```
./vet_copylocks_gen.go:39:9: EncodeMsg passes lock by value: github.com/tinylib/msgp/_generated.Foo contains sync.Mutex
./vet_copylocks_gen.go:49:9: MarshalMsg passes lock by value: github.com/tinylib/msgp/_generated.Foo contains sync.Mutex
./vet_copylocks_gen.go:87:9: Msgsize passes lock by value: github.com/tinylib/msgp/_generated.Foo contains sync.Mutex
```

Do you know why it's generating some methods using `*Foo` and others with `Foo`?

```
➜  _generated git:(go-vet-fix-copylocks-testgen) ✗ grep Foo vet_copylocks_gen.go 
func (z *Foo) DecodeMsg(dc *msgp.Reader) (err error) {
func (z Foo) EncodeMsg(en *msgp.Writer) (err error) {
func (z Foo) MarshalMsg(b []byte) (o []byte, err error) {
func (z *Foo) UnmarshalMsg(bts []byte) (o []byte, err error) {
func (z Foo) Msgsize() (s int) {
```

**Comment by shawnps-sigsci** [comment]
This is my `vet_copylocks.go`:

```
➜  _generated git:(go-vet-fix-copylocks-testgen) ✗ cat vet_copylocks.go 
package _generated

import "sync"

//go:generate msgp
//go:generate go vet

type Foo struct {
	lock sync.Mutex
}
```

**Comment by shawnps-sigsci** [comment]
@philhofer so if I embed a struct inside `Foo` like this:

```
package _generated

import "sync"

//go:generate msgp
//go:generate go vet

type Inner struct {
	Name string
}

type Foo struct {
	I    Inner
	lock sync.Mutex
}
```

all is well.

If this is acceptable I'll update the PR.

**Comment by philhofer** [comment]
There have been a bunch of requests in the past to pass stuff by value instead of by reference, and I (foolishly, perhaps) acquiesced.

For now, I think your workaround to prevent the code generator from passing your repro by value is fine. I'll have to fix the code generator to elide copies for structs that contain any of the `sync.*` types.

**Comment by shawnps-sigsci** [comment]
@philhofer I see, thank you - how does the most recent commit look? Is that what you meant by adding a test script which calls `go vet` after generating?

**Comment by philhofer** [comment]
Yep, looks good. Thanks!

**Pull request merged**
