### PR TITLE
`replace` directive

### PR DESCRIPTION
**Pull request by infastin**
Adds a `replace` directive that makes it easier to serialize foreign types.

<details>
  <summary>Example usage with github.com/google/uuid</summary>

  ```go
  package main

  import "github.com/google/uuid"

  //go:generate msgp

  //msgp:replace uuid.UUID with:UUID
  type UUID [16]byte

  // Or like that
  //msgp:replace uuid.UUID with:[16]byte

  type User struct {
    ID uuid.UUID
  }
  ```

</details> 

Also adds `any` to the list of primitives.

### CODE REVIEW

**Comment by klauspost** [comment]
So this will work when the type is a primitive?

LGTM, though.

**Review by klauspost — COMMENTED** [review]
Please add a suite of tests. Otherwise LGTM.

**Comment by infastin** [comment]
> So this will work when the type is a primitive?

Should work with any type that msgp can work with.

> Please add a suite of tests.

Added some tests.

**Review by klauspost — APPROVED** [review]
LGTM

**Comment by klauspost** [comment]
You can bump CI to 1.21 and 1.22 if that help.

**Comment by infastin** [comment]
Sorry, didn't notice it was go1.18, should be fine now.

**Comment by klauspost** [comment]
Thanks! Giving it a bit of time to see if there are any objects before merge.

**Comment by klauspost** [comment]
@infastin Seems we've picked up a conflict. Could you resolve that, and I'll merge ASAP.

**Comment by infastin** [comment]
@klauspost Resolved.

**Review by klauspost — APPROVED** [review]

**Pull request merged**
