### PR TITLE
JSON encoder may produce invalid utf-8 when provided invalid utf-8 me…

### PR DESCRIPTION
**Pull request by scunningham**
…ssage pack string.

### CODE REVIEW

**Comment by philhofer** [comment]
LGTM. Thanks.

**Comment by scunningham** [comment]
Sure, np.  @philhofer Possible to get a v1.1.2 tag?  Can pull by commit, but nicer to pull a tag.

**Comment by philhofer** [comment]
Done.

**Comment by scunningham** [comment]
Thanks!

**Pull request merged**
